version: '3.8'

services:
  backend:
    image: ghcr.io/antonyartsev/sync/backend:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - CORS_ORIGINS=https://sync.antonyartsev.com
    ports:
      - "5001:80"
    restart: unless-stopped
    networks:
      - sync-network

  frontend:
    image: ghcr.io/antonyartsev/sync/frontend:latest
    environment:
      - BACKEND_URL=https://sync.antonyartsev.com
      - Logging__LogLevel__Default=Debug
    ports:
      - "5025:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - sync-network

networks:
  sync-network:
    driver: bridge